# Generated by Django 2.2.10 on 2021-08-12 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('answers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='Пользователь', to='users.CustomUser', verbose_name='Пользователь'),
            preserve_default=False,
        ),
    ]
